kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: traefik-ingress
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v2.2
        name: traefik
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
          hostPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        # Enable dashboard without passwords, comment them for production environnements
        - --api.insecure
        - --api.dashboard

        # Providers list
        - --providers.kubernetescrd
        - --providers.kubernetesIngress.ingressClass=traefik-cert-manager

        # Entrypoints list
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443
        - --entrypoints.websecure.http.tls
        - --entrypoints.traefik.Address=:8080
        - --entrypoints.web.http.redirections.entryPoint.to=websecure
        - --entrypoints.web.http.redirections.entryPoint.scheme=https

        # Logging, change "info" for "debug" if you got troubles
        - --log.level=info